[package]
name = "rust_mastermind"
version = "0.1.0"
authors = ["Eastan Giebler <kupa528@yahoo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.2"